### ISSUE TITLE
Which versions of Godot are supported & tested?

### ISSUE THREAD

**Issue by danhealy** [V-Sekai/unidot_importer#24]
The `README.md` still indicates it should be used with 4.0 alpha builds:

> Please use the latest Godot 4.0 alpha builds ( master branch of https://github.com/godotengine/godot ) to run this addon.

This issue https://github.com/V-Sekai/unidot_importer/issues/14 implies 4.0.3 is not supported

**Comment by lyuma** [comment]
Godot 4.0.3 is supported, as are other stable builds of Godot 4.x. If you are running into problems, please file issues with the problems you have.

Sorry about the confusion in the readme. That text in the readme was left in from a year ago. I just updated the readme to indicate that Unidot does indeed work with stable builds of Godot 4, including 4.0.3.

Regarding the issue #14, it seems that the user put their engine version in the title, but the issue contains feature requests. I have edited the title to match the checklist items in that issue.

There are so many projects to work on in the purview of V-Sekai, so I haven't put much development into this project recently. Historically my contributions here have been bursty: perhaps doing a few weeks of work at a time as needed. Having issues and feature requests helps provide motivation: it's helpful to know what features are useful so I can focus time on what people need.

**Comment by danhealy** [comment]
@lyuma Thank you for clarifying 🙏and for this awesome project.  I tried using it to import a very large Synty pack with 4.1.1 and ran into a few issues, some crashes and missing content, but I will investigate further if I can narrow down the problems.
