### ISSUE TITLE
Support GraphicsMagick instead of ImageMagick

### ISSUE THREAD

**Issue by fire** [V-Sekai/unidot_importer#28]
Amend the instructions to mention [GraphicsMagick](http://www.graphicsmagick.org/) is supported.

**Comment by lyuma** [comment]
The readme is outdated, but it makes sense to support both forks.

I have generally speaking not tested texture conversion recently: It is only used for TIF and PSD support from what I understand. It would be nice for Unidot to show which files can and can't be converted and explain how to install convert if needed
