### ISSUE TITLE
Hangs on importing animation trees in certain cases

### ISSUE THREAD

**Issue by GrubLady** [V-Sekai/unidot_importer#51]
When importing certain combinations of files, Unidot seemingly hangs on the "Importing animation trees..." stage and only prints status messages repeatedly.
<img width="1564" alt="Example" src="https://github.com/V-Sekai/unidot_importer/assets/29121925/c4639ace-da40-45d4-9393-e5f07989fa37">
Sometimes I'm able to work around this by importing certain files each individually. I haven't been able to figure out what exactly causes the hang.
Using Godot 4.3-dev6, with the most recent ```main``` branch of Unidot from Github

**Comment by lyuma** [comment]
Can you hide the import dialog and check what errors are there in the Output bottom panel?

also, try pulling again: I pushed a null bugfix but not sure if it is related

**Comment by GrubLady** [comment]
Looks like it's fixed with the push of 71a6d7f9f5b4bd3deedd9d5d1fb1f01bae44dc9e!

Here's the full log from the Output panel back on the older version: https://pastebin.com/By7BhSzz
Notably, it was repeatedly printing the following error during the hang: ```res://addons/unidot_importer/package_import_dialog.gd:1410 - Cannot call method 'get_length' on a null value.```
